//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaycanLogger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaycanLogger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;OBD2&gt;
        ///  &lt;init&gt;
        ///    &lt;command send=&quot;atz&quot;&gt;&lt;/command&gt;
        ///    &lt;command send=&quot;atat1&quot;&gt;&lt;/command&gt;
        ///    &lt;command send=&quot;atsp6&quot;&gt;&lt;/command&gt;
        ///    &lt;command send=&quot;atl0&quot;&gt;&lt;/command&gt;
        ///    &lt;command send=&quot;ats0&quot;&gt;&lt;/command&gt;
        ///    &lt;command send=&quot;ath0&quot;&gt;&lt;/command&gt;
        ///    &lt;command send=&quot;ate0&quot;&gt;&lt;/command&gt;
        ///    &lt;command send=&quot;atst25&quot;&gt;&lt;/command&gt;
        ///    &lt;command send=&quot;atsh7e5&quot;&gt;&lt;/command&gt;
        ///    &lt;command send=&quot;atcm000&quot;&gt;&lt;/command&gt;
        ///    &lt;command send=&quot;atcf000&quot;&gt;&lt;/command&gt;
        ///    &lt;command send=&quot;atfcsd300000&quot;&gt;&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string obd2_TaycanSOH {
            get {
                return ResourceManager.GetString("obd2_TaycanSOH", resourceCulture);
            }
        }
    }
}
